# Generated by Django 3.1.7 on 2021-03-20 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='readed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
