# Generated by Django 3.1.7 on 2021-03-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reader',
            new_name='readers',
        ),
    ]
